pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    ttl: 7
    mount:
      #- /drone/docker
    volumes:
      - /tmp/cache:/cache

  api_tests:
    group: tests
    image: nervesproject/nerves_system_br:1.4.5
    #image: bitwalker/alpine-elixir-phoenix:latest
    environment:
      ENV: CI
      MIX_ENV: test
      ELIXIR_VERSION: 1.6.6-otp-21
    commands:
      - wget https://repo.hex.pm/builds/elixir/v$ELIXIR_VERSION.zip
      - unzip -d /usr/local/elixir v$ELIXIR_VERSION.zip
      - echo 'export PATH=/usr/local/elixir/bin:$PATH' >> $BASH_ENV
      - mix local.hex --force
      - mix local.rebar --force
      - mix archive.install hex nerves_bootstrap "~> 1.0" --force
      - mix deps.get
      - mix hex.build
      - mix compile
      #- mix nerves.artifact

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      #- /drone/docker
    volumes:
      - /tmp/cache:/cache
